name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Remove old container (if exists)
      run: |
        docker ps -a -q --filter "name=cicd-app" | grep -q . && docker rm -f cicd-app || echo "No old container found"

    - name: Remove old image (if exists)
      run: |
        docker images -q ${{ secrets.DOCKER_USERNAME }}/cicd-app:latest | grep -q . && docker rmi -f ${{ secrets.DOCKER_USERNAME }}/cicd-app:latest || echo "No old image found"

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-app:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-app:latest
